name: MERN CI

on:
  push:
    branches: [main]

jobs:
  mongo-init:
    runs-on: ubuntu-latest

    env:
      PORT: ${{secrets.PORT}}
      MONGO_URI: ${{secrets.MONGO_URI}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}


    services:
       mongo:
        image: mongo
        ports: ["27017:27017"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

          #temporary data - virtual machine
      - name: Waiting for mongodb to be ready
        run: |
          until nc -z localhost 27017; do
            echo "waiting for MongoDB..."
            sleep 2
          done
            echo "Mongodb is up"

      - name: Seed Mongodb
        working-directory: ./backend
        run: |
          npm install
          node seedTaskData.js
        
      - name: Running backend tests       
        working-directory: ./backend
        run: npm test

   
